# Generated by Django 4.0.1 on 2022-02-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tasks_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='../static/images')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
