# Generated by Django 4.0.1 on 2022-03-09 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_task_photo_task_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskName',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.task')),
            ],
            options={
                'ordering': ['complete'],
            },
            bases=('base.task',),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
