# Generated by Django 4.0.1 on 2022-03-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_taskname_alter_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskname',
            options={'ordering': ['title']},
        ),
    ]
