# Generated by Django 4.0.1 on 2022-03-09 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_taskname_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskName',
        ),
    ]
